### ISSUE TITLE
If files are missing from S3, the server fails to start

### ISSUE THREAD

**Issue by scotwk** [dconathan/madpy-deploy-ml#2]
I know this because, sigh, I forgot to run the upload step to put the models and tokenizer in place.  (It could probably be called out a little bit more in the documentation, but I didn't want to take the liberty of making that change)

What happens if you don't upload your trained model/tokenizer is this:

```
$ curl $(terraform output url)
curl: (56) Recv failure: Connection reset by peer
```

It's a confusing error because there is no indication of what is wrong and no ability to dig deeper without logging into the machine (which is not a trivial task.  It requires setting up SSH keys and modifying the security group).

After logging into the instance I found this partial stack trace in the logs:

```
[2019-04-18 18:04:45 +0000] [8] [INFO] Booting worker with pid: 8
predicting on 8 chars, 2 tokens
getting and caching tokenizer
ERROR:root:Could not find sk-deploy-ml-dev-us-east-1-models/tokenizer.pickle. Need to upload?
[2019-04-18 18:04:47 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 488, in info
    Key=key, **self.req_kw)
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 199, in _call_s3
    return method(**additional_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

Aha!  Now I know what step I forgot :)

[I put a couple of changes I made that might fix this on a branch on my fork](https://github.com/scotwk/madpy-deploy-ml/commit/79c8b2ef70b8569545881f4424c24c188140afb4), but I didn't have time to finish testing it end-to-end before I ran out of time.

**Comment by dconathan** [comment]
Yes logging is definitely a missing part of this stack/demo.  Setting up something like cloudwatch logs on an EC2 instance is kind of a pain in the butt (if anyone has an easy way I'd love to know).  You get that kind of logging "for free" when you use a container service like ECS.

But good call on the error handling!  I added a proper falcon error handler https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_error_handler 

https://github.com/dconathan/madpy-deploy-ml/commit/1e8266a5aaa483715b4c82dd3070029be049f3aa

```
$ curl localhost:8000/predict -X POST -H "content-type: application/json" -d '{"text":"hello world"}'
{"error": "FileNotFoundError: madpy-deploy-ml-a1hr8-dev-us-east-1-models/model.h5"}
```
